name: binlets-paper
channels:
  - conda-forge
  - pytorch
dependencies:
  - ipykernel
  - matplotlib
  - numba
  - numpy
  - pandas
  - python
  - pytorch::pytorch
  - pywavelets
  - scikit-image
  - scipy
  - seaborn
  - torchaudio
  - torchvision
  - pip
  - pip:
    - binlets == 1.0.0
